id: P006706
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2DB4624
  title: བདུད་རྩི་སྨན་གྱི་མདོ་ཆོག
  author: ''
  volumes:
    1c99e7d4e5c94220965d71362b7a1f91:
      image_group_id: I1PD28090
      title: ''
      volume_number: 1
      total_pages: 486
      base_file: v001.txt
